"""add website and industry column

Revision ID: 725a52755b1c
Revises: 0ab5639f21c7
Create Date: 2026-06-10 12:52:52.918563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725a52755b1c'
down_revision: Union[str, Sequence[str], None] = '0ab5639f21c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('industry', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'industry')
    op.drop_column('competitors', 'website')
    # ### end Alembic commands ###
