import os
from crewai import Agent, Task, Crew, Process
from langchain_google_genai import ChatGoogleGenerativeAI

from app.agents.tools import fetch_competitor_metrics_tool



financial_analyst=Agent(
    role="Senior Financial Analyst",
    goal="Retrieve and analyze raw corporate financial metrics to extract deep performance insights.",
    backstory="""You are an expert Wall Street quantitative analyst. You specialize in mining structured 
    corporate databases, identifying growth trends, and computing financial health indicators.""",
    tools=[fetch_competitor_metrics_tool],
    llm="gemini/gemini-3.5-flash",
    verbose=True
    )

market_strategist= Agent(
    role="Lead Market Intelligence Strategist",
    goal="Transform complex quantitative financial numbers into high-level, actionable executive summaries.",
    backstory="""You are a veteran competitive intelligence director. You excel at taking raw rows of corporate 
    financial metrics and synthesizing them into strategic positioning analysis for leadership.""",
    tools=[],  # This agent reads data passed from the analyst; needs no direct tools
    llm="gemini/gemini-3.5-flash",
    verbose=True
)

#Task Definitions

def run_competitive_analysis_crew(competitor_id: int)-> str:
    #Task 1: Extraction and Crunching

    data_extraction_task= Task(
        description=f"""Use the 'Fetch Competitor Financial Metrics' tool for competitor ID {competitor_id}. 
        Review every record returned from the database. Identify the core metrics (like Total Revenue and Net Income), 
        calculate year-over-year margins or growth rates, and flag any major anomalies or missing parameters.""",
        expected_output="A structured performance breakdown detailing exact values, growth rates, and health calculations.",
        agent=financial_analyst
    )

    # Task 2: Strategic Synthesis
    executive_reporting_task = Task(
        description="""Review the quantitative performance breakdown generated by the Senior Financial Analyst. 
        Synthesize these findings into a pristine, C-suite ready Competitive Intelligence Report. 
        Highlight structural strengths, vulnerabilities, and an overall strategic market outlook.""",
        expected_output="A professional, markdown-formatted Executive Market Intelligence Report.",
        agent=market_strategist
    )

    # Assemble the crew
    market_spy_crew= Crew(
        agents=[financial_analyst,market_strategist],
        tasks=[data_extraction_task, executive_reporting_task],
        process=Process.sequential, #analyze run first,then passes finding to strategist
        verbose=True
    )
    # Fire up the execution loop
    return market_spy_crew.kickoff()